FRAMEWORK_MODULES=./base/... ./owiz/... ./core/... ./http/... ./chenile/... ./bdd-utils/... ./config/... ./middleware/... ./stm/... ./stateentity/... ./servicegen/... ./packager/...

.PHONY: test
test:
	@echo "Testing framework modules..."
	cd chenile-framework && go test $(FRAMEWORK_MODULES)
	@echo "Testing example services..."
	cd chenile-examples/customer-service && go test ./...
	cd chenile-examples/inventory-service && go test ./...
	cd chenile-examples/order-service && go test ./...
	cd chenile-examples/state-order-service && go test ./...
	cd chenile-examples/mainweb-app && go test ./...

.PHONY: coverage
coverage:
	cd chenile-framework && go test -cover $(FRAMEWORK_MODULES)
	cd chenile-examples/customer-service && go test -cover ./...
	cd chenile-examples/inventory-service && go test -cover ./...
	cd chenile-examples/order-service && go test -cover ./...
	cd chenile-examples/state-order-service && go test -cover ./...
	cd chenile-examples/mainweb-app && go test -cover ./...

.PHONY: generate-example
generate-example:
	cd chenile-framework/servicegen && go run ./cmd/chenile-servicegen new --name inventory --out ../../chenile-examples
